apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      containers:
      - name: nats
        image: nats-streaming:0.17.0
        # array of arguments that is provided to the primary command that gets executed
        # when a container is built out of our image
        # the options that go into this array can be found in the documentation
        # https://hub.docker.com/_/nats-streaming#:~:text=the%20first%20output.-,Commandline%20Options,-Streaming%20Server%20Options
        args: [
          "-p", "4222",
          "-m", "8222",
          # -hbi is the interval at which the server will send heartbeats to its clients
          "-hbi", "5s",
          # -hbt is the timeout after which the server will consider a client to be dead
          "-hbt", "5s",
          "-hbf", "2",
          "-SD",
          "-cid", "ticketing"
        ]
---
apiVersion: v1
kind: Service
metadata:
  name: nats-srv
spec:
  selector:
    app: nats
  ports:
      # this is the port that the nats server is listening on
      # we can port forward this port to test against it
    - name: client
      protocol: TCP
      port: 4222
      targetPort: 4222
      # this is the port that we will use to connect to the nats server
      # from the outside world, so we can look at the traffic
      # need to port forward this port to be able to see the traffic
      # http://localhost:8222/streaming can view info here in the browser
    - name: monitoring
      protocol: TCP
      port: 8222
      targetPort: 8222